import { User, Patient, DoctorReview } from './types';

export const DEMO_USERS: User[] = [
  {
    id: 'nurse-1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@facility.com',
    role: 'nurse',
    department: 'Ward A',
    phone: '+1-555-0101',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'nurse-2',
    name: 'Michael Chen',
    email: 'michael.chen@facility.com',
    role: 'nurse',
    department: 'Ward B',
    phone: '+1-555-0102',
    createdAt: new Date('2024-02-10'),
  },
  {
    id: 'doctor-1',
    name: 'Dr. Emily Roberts',
    email: 'emily.roberts@facility.com',
    role: 'doctor',
    department: 'Internal Medicine',
    phone: '+1-555-0201',
    createdAt: new Date('2024-01-10'),
  },
  {
    id: 'doctor-2',
    name: 'Dr. James Wilson',
    email: 'james.wilson@facility.com',
    role: 'doctor',
    department: 'Emergency Medicine',
    phone: '+1-555-0202',
    createdAt: new Date('2024-01-12'),
  },
  {
    id: 'admin-1',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@facility.com',
    role: 'admin',
    department: 'Administration',
    phone: '+1-555-0301',
    createdAt: new Date('2024-01-05'),
  },
  {
    id: 'super-admin-1',
    name: 'Robert Kumar',
    email: 'robert.kumar@facility.com',
    role: 'super-admin',
    department: 'System Administration',
    phone: '+1-555-0401',
    createdAt: new Date('2023-12-01'),
  },
];

function generateTemperatureRecords(
  patientId: string,
  startDate: Date,
  nurseName: string,
  pattern: 'improving' | 'stable' | 'worsening' | 'critical'
) {
  const records = [];
  let baseTemp = 38.5;

  for (let i = 0; i < 7; i++) {
    const recordDate = new Date(startDate);
    recordDate.setDate(recordDate.getDate() - (6 - i));

    let temp = baseTemp;
    if (pattern === 'improving') {
      temp = 38.5 - i * 0.3;
    } else if (pattern === 'worsening') {
      temp = 37.8 + i * 0.3;
    } else if (pattern === 'critical') {
      temp = 40.2 + (i % 2) * 0.5;
    } else {
      temp = 37.8 + (Math.random() - 0.5) * 0.4;
    }

    records.push({
      id: `temp-${patientId}-${i}`,
      patientId,
      temperature: Math.round(temp * 10) / 10,
      recordedAt: recordDate,
      recordedBy: nurseName,
      notes: i === 0 ? 'Initial assessment' : undefined,
    });
  }

  return records;
}

export const DEMO_PATIENTS: Patient[] = [
  {
    id: 'pat-001',
    name: 'James Martin',
    age: 45,
    gender: 'M',
    admissionDate: new Date('2024-05-14'),
    status: 'under-treatment',
    ward: 'Ward A',
    bedNumber: 'A-01',
    contact: '+1-555-1001',
    emergencyContact: '+1-555-1002',
    symptoms: ['High fever', 'Cough', 'Fatigue'],
    medicalHistory: 'Hypertension',
    temperatureRecords: generateTemperatureRecords(
      'pat-001',
      new Date('2024-05-21'),
      'Sarah Johnson',
      'improving'
    ),
  },
  {
    id: 'pat-002',
    name: 'Maria Garcia',
    age: 32,
    gender: 'F',
    admissionDate: new Date('2024-05-18'),
    status: 'ready-for-discharge',
    ward: 'Ward A',
    bedNumber: 'A-02',
    contact: '+1-555-1003',
    emergencyContact: '+1-555-1004',
    symptoms: ['Mild fever', 'Headache'],
    temperatureRecords: [
      {
        id: 'temp-pat-002-1',
        patientId: 'pat-002',
        temperature: 36.8,
        recordedAt: new Date('2024-05-16'),
        recordedBy: 'Sarah Johnson',
      },
      {
        id: 'temp-pat-002-2',
        patientId: 'pat-002',
        temperature: 36.9,
        recordedAt: new Date('2024-05-17'),
        recordedBy: 'Sarah Johnson',
      },
      {
        id: 'temp-pat-002-3',
        patientId: 'pat-002',
        temperature: 37.0,
        recordedAt: new Date('2024-05-18'),
        recordedBy: 'Sarah Johnson',
      },
      {
        id: 'temp-pat-002-4',
        patientId: 'pat-002',
        temperature: 37.1,
        recordedAt: new Date('2024-05-19'),
        recordedBy: 'Michael Chen',
      },
      {
        id: 'temp-pat-002-5',
        patientId: 'pat-002',
        temperature: 36.9,
        recordedAt: new Date('2024-05-20'),
        recordedBy: 'Michael Chen',
      },
      {
        id: 'temp-pat-002-6',
        patientId: 'pat-002',
        temperature: 36.8,
        recordedAt: new Date('2024-05-21'),
        recordedBy: 'Sarah Johnson',
      },
    ],
  },
  {
    id: 'pat-003',
    name: 'David Thompson',
    age: 58,
    gender: 'M',
    admissionDate: new Date('2024-05-19'),
    status: 'under-treatment',
    ward: 'Ward B',
    bedNumber: 'B-01',
    contact: '+1-555-1005',
    emergencyContact: '+1-555-1006',
    symptoms: ['High fever', 'Severe cough', 'Chest pain'],
    medicalHistory: 'Diabetes, Heart condition',
    temperatureRecords: generateTemperatureRecords(
      'pat-003',
      new Date('2024-05-21'),
      'Michael Chen',
      'critical'
    ),
  },
  {
    id: 'pat-004',
    name: 'Sarah Lee',
    age: 29,
    gender: 'F',
    admissionDate: new Date('2024-05-12'),
    status: 'under-treatment',
    ward: 'Ward A',
    bedNumber: 'A-03',
    contact: '+1-555-1007',
    emergencyContact: '+1-555-1008',
    symptoms: ['Moderate fever', 'Sore throat'],
    temperatureRecords: generateTemperatureRecords(
      'pat-004',
      new Date('2024-05-21'),
      'Sarah Johnson',
      'stable'
    ),
  },
  {
    id: 'pat-005',
    name: 'Robert Brown',
    age: 67,
    gender: 'M',
    admissionDate: new Date('2024-05-10'),
    status: 'discharged',
    ward: 'Ward B',
    bedNumber: 'B-02',
    contact: '+1-555-1009',
    emergencyContact: '+1-555-1010',
    symptoms: ['High fever', 'Weakness'],
    dischargeDate: new Date('2024-05-20'),
    dischargeNotes: 'Recovered well. Advised rest and follow-up in 2 weeks.',
    temperatureRecords: generateTemperatureRecords(
      'pat-005',
      new Date('2024-05-20'),
      'Michael Chen',
      'improving'
    ),
  },
  {
    id: 'pat-006',
    name: 'Patricia White',
    age: 51,
    gender: 'F',
    admissionDate: new Date('2024-05-15'),
    status: 'under-treatment',
    ward: 'Ward A',
    bedNumber: 'A-04',
    contact: '+1-555-1011',
    emergencyContact: '+1-555-1012',
    symptoms: ['Fever', 'Fatigue', 'Body aches'],
    medicalHistory: 'Asthma',
    temperatureRecords: generateTemperatureRecords(
      'pat-006',
      new Date('2024-05-21'),
      'Sarah Johnson',
      'improving'
    ),
  },
  {
    id: 'pat-007',
    name: 'Christopher Davis',
    age: 38,
    gender: 'M',
    admissionDate: new Date('2024-05-16'),
    status: 'under-treatment',
    ward: 'Ward B',
    bedNumber: 'B-03',
    contact: '+1-555-1013',
    emergencyContact: '+1-555-1014',
    symptoms: ['Moderate fever', 'Cough'],
    temperatureRecords: generateTemperatureRecords(
      'pat-007',
      new Date('2024-05-21'),
      'Michael Chen',
      'stable'
    ),
  },
  {
    id: 'pat-008',
    name: 'Jennifer Miller',
    age: 44,
    gender: 'F',
    admissionDate: new Date('2024-05-11'),
    status: 'discharged',
    ward: 'Ward A',
    bedNumber: 'A-05',
    contact: '+1-555-1015',
    emergencyContact: '+1-555-1016',
    symptoms: ['Fever'],
    dischargeDate: new Date('2024-05-19'),
    dischargeNotes: 'Good recovery. Discharged with antibiotics.',
    temperatureRecords: generateTemperatureRecords(
      'pat-008',
      new Date('2024-05-19'),
      'Sarah Johnson',
      'improving'
    ),
  },
  {
    id: 'pat-009',
    name: 'Michael Johnson',
    age: 35,
    gender: 'M',
    admissionDate: new Date('2024-05-17'),
    status: 'ready-for-discharge',
    ward: 'Ward B',
    bedNumber: 'B-04',
    contact: '+1-555-1017',
    emergencyContact: '+1-555-1018',
    symptoms: ['Mild fever'],
    temperatureRecords: [
      {
        id: 'temp-pat-009-1',
        patientId: 'pat-009',
        temperature: 37.2,
        recordedAt: new Date('2024-05-18'),
        recordedBy: 'Michael Chen',
      },
      {
        id: 'temp-pat-009-2',
        patientId: 'pat-009',
        temperature: 37.0,
        recordedAt: new Date('2024-05-19'),
        recordedBy: 'Michael Chen',
      },
      {
        id: 'temp-pat-009-3',
        patientId: 'pat-009',
        temperature: 36.9,
        recordedAt: new Date('2024-05-20'),
        recordedBy: 'Sarah Johnson',
      },
      {
        id: 'temp-pat-009-4',
        patientId: 'pat-009',
        temperature: 36.8,
        recordedAt: new Date('2024-05-21'),
        recordedBy: 'Michael Chen',
      },
    ],
  },
  {
    id: 'pat-010',
    name: 'Amanda Taylor',
    age: 26,
    gender: 'F',
    admissionDate: new Date('2024-05-20'),
    status: 'admitted',
    ward: 'Ward A',
    bedNumber: 'A-06',
    contact: '+1-555-1019',
    emergencyContact: '+1-555-1020',
    symptoms: ['High fever', 'Cough', 'Chills'],
    temperatureRecords: [
      {
        id: 'temp-pat-010-1',
        patientId: 'pat-010',
        temperature: 39.2,
        recordedAt: new Date('2024-05-20'),
        recordedBy: 'Sarah Johnson',
      },
    ],
  },
  {
    id: 'pat-011',
    name: 'Kevin Anderson',
    age: 50,
    gender: 'M',
    admissionDate: new Date('2024-05-13'),
    status: 'under-treatment',
    ward: 'Ward B',
    bedNumber: 'B-05',
    contact: '+1-555-1021',
    emergencyContact: '+1-555-1022',
    symptoms: ['Fever', 'Weakness', 'Loss of appetite'],
    medicalHistory: 'Hypertension',
    temperatureRecords: generateTemperatureRecords(
      'pat-011',
      new Date('2024-05-21'),
      'Michael Chen',
      'improving'
    ),
  },
  {
    id: 'pat-012',
    name: 'Lisa Martinez',
    age: 40,
    gender: 'F',
    admissionDate: new Date('2024-05-08'),
    status: 'discharged',
    ward: 'Ward A',
    bedNumber: 'A-07',
    contact: '+1-555-1023',
    emergencyContact: '+1-555-1024',
    symptoms: ['High fever'],
    dischargeDate: new Date('2024-05-18'),
    dischargeNotes: 'Patient recovered well. Continue prescribed medications.',
    temperatureRecords: generateTemperatureRecords(
      'pat-012',
      new Date('2024-05-18'),
      'Sarah Johnson',
      'improving'
    ),
  },
  {
    id: 'pat-013',
    name: 'George Wilson',
    age: 62,
    gender: 'M',
    admissionDate: new Date('2024-05-17'),
    status: 'under-treatment',
    ward: 'Ward B',
    bedNumber: 'B-06',
    contact: '+1-555-1025',
    emergencyContact: '+1-555-1026',
    symptoms: ['Moderate fever', 'Fatigue'],
    medicalHistory: 'Diabetes',
    temperatureRecords: generateTemperatureRecords(
      'pat-013',
      new Date('2024-05-21'),
      'Michael Chen',
      'stable'
    ),
  },
  {
    id: 'pat-014',
    name: 'Nicole Harris',
    age: 33,
    gender: 'F',
    admissionDate: new Date('2024-05-19'),
    status: 'under-treatment',
    ward: 'Ward A',
    bedNumber: 'A-08',
    contact: '+1-555-1027',
    emergencyContact: '+1-555-1028',
    symptoms: ['High fever', 'Cough'],
    temperatureRecords: generateTemperatureRecords(
      'pat-014',
      new Date('2024-05-21'),
      'Sarah Johnson',
      'improving'
    ),
  },
  {
    id: 'pat-015',
    name: 'Edward Clark',
    age: 55,
    gender: 'M',
    admissionDate: new Date('2024-05-14'),
    status: 'under-treatment',
    ward: 'Ward B',
    bedNumber: 'B-07',
    contact: '+1-555-1029',
    emergencyContact: '+1-555-1030',
    symptoms: ['Fever', 'Sore throat', 'Headache'],
    medicalHistory: 'Heart disease',
    temperatureRecords: generateTemperatureRecords(
      'pat-015',
      new Date('2024-05-21'),
      'Michael Chen',
      'stable'
    ),
  },
  {
    id: 'pat-016',
    name: 'Rachel Green',
    age: 28,
    gender: 'F',
    admissionDate: new Date('2024-05-21'),
    status: 'admitted',
    ward: 'Ward A',
    bedNumber: 'A-09',
    contact: '+1-555-1031',
    emergencyContact: '+1-555-1032',
    symptoms: ['High fever', 'Chills', 'Body aches'],
    temperatureRecords: [
      {
        id: 'temp-pat-016-1',
        patientId: 'pat-016',
        temperature: 38.9,
        recordedAt: new Date('2024-05-21'),
        recordedBy: 'Sarah Johnson',
      },
    ],
  },
  {
    id: 'pat-017',
    name: 'William Rodriguez',
    age: 47,
    gender: 'M',
    admissionDate: new Date('2024-05-16'),
    status: 'under-treatment',
    ward: 'Ward B',
    bedNumber: 'B-08',
    contact: '+1-555-1033',
    emergencyContact: '+1-555-1034',
    symptoms: ['Moderate fever', 'Cough', 'Congestion'],
    temperatureRecords: generateTemperatureRecords(
      'pat-017',
      new Date('2024-05-21'),
      'Michael Chen',
      'improving'
    ),
  },
  {
    id: 'pat-018',
    name: 'Catherine Lewis',
    age: 36,
    gender: 'F',
    admissionDate: new Date('2024-05-12'),
    status: 'discharged',
    ward: 'Ward A',
    bedNumber: 'A-10',
    contact: '+1-555-1035',
    emergencyContact: '+1-555-1036',
    symptoms: ['Fever', 'Cough'],
    dischargeDate: new Date('2024-05-21'),
    dischargeNotes: 'Fully recovered. Resume normal activities gradually.',
    temperatureRecords: generateTemperatureRecords(
      'pat-018',
      new Date('2024-05-21'),
      'Sarah Johnson',
      'improving'
    ),
  },
  {
    id: 'pat-019',
    name: 'Thomas Hall',
    age: 41,
    gender: 'M',
    admissionDate: new Date('2024-05-18'),
    status: 'ready-for-discharge',
    ward: 'Ward B',
    bedNumber: 'B-09',
    contact: '+1-555-1037',
    emergencyContact: '+1-555-1038',
    symptoms: ['Mild fever'],
    temperatureRecords: [
      {
        id: 'temp-pat-019-1',
        patientId: 'pat-019',
        temperature: 37.3,
        recordedAt: new Date('2024-05-18'),
        recordedBy: 'Michael Chen',
      },
      {
        id: 'temp-pat-019-2',
        patientId: 'pat-019',
        temperature: 37.1,
        recordedAt: new Date('2024-05-19'),
        recordedBy: 'Michael Chen',
      },
      {
        id: 'temp-pat-019-3',
        patientId: 'pat-019',
        temperature: 36.9,
        recordedAt: new Date('2024-05-20'),
        recordedBy: 'Sarah Johnson',
      },
      {
        id: 'temp-pat-019-4',
        patientId: 'pat-019',
        temperature: 36.7,
        recordedAt: new Date('2024-05-21'),
        recordedBy: 'Michael Chen',
      },
    ],
  },
  {
    id: 'pat-020',
    name: 'Victoria Young',
    age: 31,
    gender: 'F',
    admissionDate: new Date('2024-05-20'),
    status: 'admitted',
    ward: 'Ward A',
    bedNumber: 'A-11',
    contact: '+1-555-1039',
    emergencyContact: '+1-555-1040',
    symptoms: ['High fever', 'Severe cough'],
    temperatureRecords: [
      {
        id: 'temp-pat-020-1',
        patientId: 'pat-020',
        temperature: 39.5,
        recordedAt: new Date('2024-05-20'),
        recordedBy: 'Sarah Johnson',
      },
    ],
  },
];
